[package]
name = "deployer"
version = "0.1.0"
authors = ["Ian Macalinao <ian@deploydao.com>"]
license = "Apache-2.0"

[addresses]
deployer = "0x35bf5e9ec8b7a342900f55e4cc08ee1d7d90c7ae7daeaf19e298f11c957aba07"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "e1c6a5713301ed72bf3a846ab9536d002ac801d6"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "e1c6a5713301ed72bf3a846ab9536d002ac801d6"

[dev-dependencies.aptest]
git = "https://github.com/aptosis/aptest.git"
rev = "3548fe2fd66f54b159a3a2f5eb0a88818c37b719"
