[package]
name = "Deployer"
version = "0.1.0"

[addresses]
Std = "0x1"
AptosFramework = "0x1"
Deployer = "0xcf43589ea2a37ecab7c39657db15939e23e93972bc0481b51c4797c1f2d78a75"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "49f08c7419b442461e47164848305fe74e846607"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "49f08c7419b442461e47164848305fe74e846607"
