[package]
name = "Deployer"
version = "0.1.0"

[addresses]
Std = "0x1"
AptosFramework = "0x1"
Deployer = "0x05207462c952da0e04d39ca87e450f6d3ffd699e8d81ff4923e1093965e4a182"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "49f08c7419b442461e47164848305fe74e846607"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "49f08c7419b442461e47164848305fe74e846607"
